
name: Tourism ML Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r tourism_project/deployment/requirements.txt

    - name: Data Preparation
      run: python tourism_project/model_building/prep.py

    - name: Train Model
      run: python tourism_project/model_building/train.py
